### ISSUE TITLE
JackTrip Library

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#159]
I've started the big project of splitting jacktrip into a library and a client. The goal is that the client only has to include one jacktrip header file that does the networking stuff. The interface to any audio platform (like Jack or CoreAudio) should be generic in the end. The library just fills the audio buffer with what is in the network buffer for that channel. Adding or removing a channel to a connection should be as easy as `connection->add_audio_channel();` or `connection->add_osc_channel();`. I have setups in mind where a client only sends one channel but receives two. But in the future we also want to send osc messages to the server.

This meta issue is for dicussion as well as bookkeeping the progress. Splitting up the effort into smaller PRs helps reducing the divergence to the rest of the development.

### TODO
- [x] Split client and library #157 
- [ ] Write example client
- [ ] Move audio parts out of the library
- [ ] Design a well thought API -> dynamic management of connections and channels
- [ ] Move jacktrip modes out of the library
    - [ ] no difference between server and client from the perspective of the library
    - [ ] differences of server and client are managed in the client
- [ ] Add UUIDs, unique names, allow and deny lists, etc.
- [ ] Add rooms
- [ ] Move from QT to std
- [ ] Add binding generator for other languages like Python, etc. (e.g. SWIG)

**Comment by vrslev** [comment]
@ntonnaett Hey! 👋 Is this being worked on? I love JackTrip and really want to be able to access it with an C API.

**Comment by cchafe** [comment]
I second that, however, it's going to be awhile (at least,  I'm not aware of any current work).

**Comment by vrslev** [comment]
Got it. Thanks for your response!

**Comment by rodneydup** [comment]
Just adding my support for this. I would love to see jacktrip as a library! I am working on some network music applications (C++) and it would be amazing to have jacktrip integrated into them instead of needing to have the jacktrip client installed separately and then needing to connect audio streams between my applications and jacktrip through JACK. 

I tried a few things using the jacktrip repository as it is and I hit a wall in my programming abilities and time when I couldn't get to the point of compiling as a library.
